[package]
name = "euler_criterion"
version = "0.0.0"
authors = ["Jorge Aparicio <japaric@linux.com>"]

[dependencies.criterion]
git = "https://github.com/japaric/criterion.rs"

[dependencies]
env_logger = "*"
log = "*"
rustc-serialize = "*"
tempdir = "*"
