[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "euler"
version = "0.0.0"

[dependencies]
debug_unreachable = "*"
env_logger = "*"
log = "*"
rustc-serialize = "*"
tempdir = "*"

[dependencies.criterion]
git = "https://github.com/japaric/criterion.rs"
