[package]
name = "euler_criterion"
version = "0.0.0"
authors = ["Jorge Aparicio <japaric@linux.com>"]

[dependencies]
log = "*"

[dependencies.criterion]
git = "https://github.com/japaric/criterion.rs"

[profile.dev]
debug = false
