# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

require "problem"

problem 2 do
  code do
    fibonacci = [1, 2]
    loop do
      next_fib = (fibonacci[-1] + fibonacci[-2])
      break unless next_fib < 4_000_000
      fibonacci << next_fib
    end
    fibonacci.select { |i| i.even? }.sum
  end
  expect 4613732
end
